### ISSUE TITLE
Can't Fetch The Jar

### ISSUE THREAD

**Issue by yanayirrifai** [adaa-polsl/RuleKit#2]
Fetching latest RuleKit release version:  v1.7.0
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/rulekit/__main__.py", line 70, in <module>
    _main()
  File "/usr/local/lib/python3.10/dist-packages/rulekit/__main__.py", line 61, in _main
    _download_rulekit_jar()
  File "/usr/local/lib/python3.10/dist-packages/rulekit/__main__.py", line 31, in _download_rulekit_jar
    raise ValueError('Failed to fetch latest RuleKit release jar file.')
ValueError: Failed to fetch latest RuleKit release jar file.
ERROR:RuleKit:Failed to load jar files

**Comment by agudys** [comment]
Hello! I have reuploaded JAR file. Could you please check if it works now?

**Comment by yanayirrifai** [comment]
it already works now, thank you
